### PR TITLE
FIX: Insidious bug in the caching logic

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by tacaswell** [comment]
I think the solution is to remove the cache logic from `past` all together.

The cache gets mutated on assignment and as part of `__init__`, past should just provide a view into the past.

**Comment by danielballan** [comment]
I don't know, we have the cache, we might as well use the performance optimization. It's not too subtle to make sure this is working correctly.

**Comment by tacaswell** [comment]
You get the benefit from the cache when you use [].  Looking at this a bit
more carefully, this test will only be hit as part of the `__init__` as
`num_back == 0` is short-circuited a few lines above and the `__init__`
function takes care of populating the cache.

That this here at all is an artifact of when we discovered that sqlite is
not thread safe and I changed `__getitem__` from just calling past to
looking at the cache.  The original cache was lazy (didn't populate
`_cache` until you looked at / assigned that key) to aggressive (filling it
in `__init__`).

**Comment by danielballan** [comment]
OK, I'm sold. New commit removing caching logic from `past`.

**Pull request merged**
