### PR TITLE
Remove unused imports. Win compatibility for testing

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Turns out we're not actually using six

**Comment by ericdill** [comment]
Just amended the last commit to add an-line comment regarding why the change was made.  Tests passed before this commit was amended and force-pushed, so this is ready for review @tacaswell @danielballan @klauer

**Comment by danielballan** [comment]
Good catch with testing the wrong version of Python. I would advocate vendoring or requiring weakrefmethod rather than committing to dropping 2.x support.

**Comment by tacaswell** [comment]
This makes me a bit worried about the rest of our travis setups in that we may be testing less things on python2 than we think...

**Comment by ericdill** [comment]
@tacaswell in most/all of the other .travis.yml's we have a line that is essentially `conda create -n testenv python=$TRAVIS_PYTHON_VERSION <deps> ...`

That line was missing here which is why we were not testing other pythons

**Comment by ericdill** [comment]
but you do raise a valid point. I'll add that (check other travis ymls) to my list of things to do

**Comment by tacaswell** [comment]
And I would be in favor of just making the use of weakref conditional, PR on PR coming

**Comment by ericdill** [comment]
Yay 2.7 is working again. Thanks @tacaswell .  Self-merging so I can finish this up at conda forge

**Comment by ericdill** [comment]
Thanks for the review @danielballan @tacaswell

**Pull request merged**
