### PR TITLE
FIX: commit the query to delete keys

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
How to reproduce bug:
```py3
from historydict import HistoryDict

def mkfoobar(val):
    filename  = 'myfile1234'
    h = HistoryDict(filename)
    h['foo'] = val
    return h
    
def delfoobar():
    filename  = 'myfile1234'
    h = HistoryDict(filename)
    del h['foo']
    return h
    
h = mkfoobar('a')
print("foo: {}".format(h['foo']))
delfoobar()
print("foo after delete: {}".format(h['foo']))
h = mkfoobar('b')
print("foo after changing: {}".format(h['foo']))

print("Now deleting foo, and keeping ref of history dict")
h = delfoobar()
```

```py3
In [1]: %run test_bug.py
foo: a
foo after delete: a
foo after changing: b
Now deleting foo, and keeping ref of history dict
Exception ignored in: <bound method HistoryDict.__del__ of {'foo': 'b'}>
Traceback (most recent call last):
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 185, in __del__
    self.flush()
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 178, in flush
    [self._flush(key) for key in self]
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 178, in <listcomp>
    [self._flush(key) for key in self]
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 182, in _flush
    self[key] = value
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 87, in __setitem__
    return self._put(key, val)
  File "/home/lhermitte/miniconda3/envs/py3/lib/python3.6/site-packages/historydict.py", line 157, in _put
    self._conn.execute(INSERTION_QUERY, (hk, hk, data_str))  # yes, twice
sqlite3.OperationalError: database is locked

In [2]: %debug
ERROR:root:No traceback has been produced, nothing to debug.

In [3]: 
```

**Comment by jrmlhermitte** [comment]
looks good to me. 3.7 nightly didn't build (looks like it's an issue with setuptools)
We should also update to py3.6 #33

**Comment by jrmlhermitte** [comment]
is it okay to tag this a new version and patch this in to a new colection environment?

**Comment by danielballan** [comment]
Go for it, @jrmlhermitte. Ping me when it's tagged and I'll upload to PyPI as well.

**Comment by jrmlhermitte** [comment]
Sure thing. thanks!
here's the PR:
https://github.com/NSLS-II/lightsource2-recipes/pull/281

feel free to edit the release notes:
https://github.com/Nikea/historydict/releases/tag/v1.2.2

**Pull request merged**
