### PR TITLE
ENH: Add flush to support mutable values.

### PR DESCRIPTION
**Pull request by danielballan**
all credit to @klauer -- this commit is a simplified version
of his idea in this comment:
https://github.com/NSLS-II/bluesky/issues/355#issuecomment-188382421

includes tests and README update

### CODE REVIEW

**Comment by ericdill** [comment]
:+1: from me 

@ambarb this will make historydict behave like you (rightfully) expected in nsls-ii/bluesky#355

**Comment by tacaswell** [comment]
https://docs.python.org/3.5/reference/datamodel.html#object.__del__  The last sentence makes me a bit nervous about this always working in the normal case (where the interpreter shuts down cleanly).

**Comment by klauer** [comment]
@tacaswell, that's a valid concern, I think. But what's the worst-case scenario? As is, the functionality without the PR is _definitely_ not what the user expects (in the case of mutables).

**Comment by danielballan** [comment]
I think this addresses @tacaswell's point. Unfortunately it's very hard to test the situation where `__del__` is not called. My new commit should handle that case, and in interactive tests I performed it at least did no harm.

**Comment by danielballan** [comment]
P.S. In Python 3.2+ there is a new `atexit.unregister` that we could be using, but if you'll take my word for it, stashing a reference to unregister became messy. Relying on weakref here seems sufficient to me.

(Some Travis builds are failing on a network-related error in the `conda build ...` step. The actual tests are fine.)

**Comment by danielballan** [comment]
Are people comfortable with this approach? It sounds to me like @klauer is on board. I suspect we all forgot about this. CSX would like it.

**Comment by klauer** [comment]
Could probably use a bit more thorough testing, but I'm 👍 as you suspected.

**Comment by danielballan** [comment]
Any ideas how to test this better? I'll for it but I'm out of ideas.

**Comment by klauer** [comment]
Hand it over to a beamline scientist : )

**Pull request merged**
