### PR TITLE
add CI for 2.6 and 3.3

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by tacaswell** [comment]
Not sure it is worth supporting 2.6.

While you are at it can you also add ci for 3.5 betas?

**Comment by ericdill** [comment]
I was mostly curious to see if it just **worked** out of the box.  The unit testing framework seems to be righteously broken on 2.6, so I am :+1: for not including it on travis.  How do I include 3.5 betas?

**Comment by ericdill** [comment]
Just looked at mpl's travis yml. Do you want `"3.5.0b4"`?

**Comment by tacaswell** [comment]
Yes, that seems to be more reliable than the nightly (which is about to
switch over to targeting 3.6 anyway).

**Comment by ericdill** [comment]
Great, this should be good to go then

**Pull request merged**
