### PR TITLE
DOC: sphinx skeleton

### PR DESCRIPTION
**Pull request by tacaswell**
Can probably move most of the readme content over with minimal changes.

### CODE REVIEW

**Comment by danielballan** [comment]
I'll throw some commits into this.

**Comment by ericdill** [comment]
@danielballan were you going to add stuff to this? Or should this be merged?

**Comment by danielballan** [comment]
Needs README content before merging. Not a top priority unfortunately.

**Comment by ericdill** [comment]
What sort of README content were you thinking?

**Comment by danielballan** [comment]
I mean, we need to copy the contents of the README (usage examples, etc) into the docs somewhere.

**Comment by tacaswell** [comment]
We are abandoning this project over all and this PR has not been touched for 4.5 years, closing.

**Pull request closed without merging**
